version: '3.7'
services:
  guidance:
    build:
      context: ./singularity/docker
      dockerfile: GuidanceDockerfile
    container_name: guidance
    expose:
      - "22"
    volumes:
      - ".:/guidance"
      - "./tmp:/tmp"
      - "./logs:/logs"
    command: ["/bin/bash", "-c", "/guidance/utils/launch_examples/docker_example.sh > /logs/test.out 2> /logs/test.err"]
    
    
