version: '3.7'
services:
  guidance:
    build:
      context: ./singularity/docker
      dockerfile: GuidanceDockerfile
    container_name: guidance
    expose:
      - "22"
    volumes:
      - ".:/guidance"
      - "./tmp:/tmp"
    command: ["/bin/bash", "/guidance/utils/launch_examples/docker_example.sh"]
    
    
